apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: simple-web-service-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: simple-web-service-cluster-ip
          servicePort: 80
