apiVersion: v1
kind: Service
metadata:
  name: simple-web-service-cluster-ip
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: simple-web-service
  type: ClusterIP
